const assert = require('node:assert/strict');
const { VirtualConsole } = require('jsdom');
const { bootApp } = require('./helpers/boot');
const path = require('node:path');
const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
(async () => {
  const errors=[]; const vc=new VirtualConsole(); vc.on('jsdomError',e=>{if(!/scrollTo|Not implemented|Could not load|getaddrinfo/i.test(e.message))errors.push(e.message)}); vc.on('error',(...a)=>errors.push(a.join(' ')));
  const dom=await bootApp(path.join(__dirname,'..','index.html'),{virtualConsole:vc}); await wait(1500);
  const p=dom.window.CWB.importer.previewCSV('序号1,序号2,姓名,学号,社区/书院,危机预警级别,是否解除预警\n1,A,张三,20240001,东区书院,二级,否','students');
  assert.ok(p.mapped.includes('full_name') && p.mapped.includes('student_number'), '姓名/学号 must map');
  assert.ok(p.mapped.includes('community') && p.mapped.includes('crisis_level') && p.mapped.includes('crisis_relieved'), '社区/书院、危机预警级别、是否解除预警 must map');
  assert.equal(p.summary.ready, 1);
  assert.equal(p.rows[0].value.student_number, '20240001');
  assert.equal(p.rows[0].value.community, '东区书院');
  assert.equal(p.rows[0].value.crisis_level, '二级');
  assert.equal(p.rows[0].value.crisis_relieved, false, '「否」must normalize to false');
  const run = dom.window.CWB.importer.commitPreview(p.id, { skipInvalid:true, conflictPolicy:'skip', confirmSensitive:true });
  assert.equal(run.ok, true, run.error || 'commit must succeed');
  const student = dom.window.CWB.db.students.find(s => s.student_number === '20240001');
  assert.ok(student, 'imported student must exist');
  assert.equal(student.community, '东区书院');
  assert.equal(student.crisis_level, '二级');
  assert.equal(student.crisis_relieved, false);
  assert.equal(student.custom_fields['custom_序号1_1'], '1', 'serial-looking columns become custom fields, not lost');
  assert.equal(student.custom_fields['custom_序号2_2'], 'A');
  assert.equal(Object.keys(student).some(k => k === '序号1' || k === '1' || k === 'A'), false, 'serial values must not pollute record top level');
  assert.deepEqual(errors,[]); dom.window.close(); console.log('PASS v4-import');
})().catch(e=>{console.error(e.stack||e.message);process.exit(1)});